### ISSUE TITLE
Python: Mismatched input 'def' expecting INDENT

### ISSUE THREAD

**Issue by GlowarionHelfer** [Glowdragon/GlowarionIssues#144]
**[org.python.core.PySyntaxError]**
Error while interpreting the python script of quest emmie_findtheflower
SyntaxError: ("mismatched input 'def' expecting INDENT", ('<string>', 3, 0, 'def onSecondStart(second):\n'))

    at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95)
    at org.python.core.ParserFacade.parse(ParserFacade.java:205)
    at org.python.core.Py.compile_flags(Py.java:1976)
    at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
    at net.glowarion.engine.quest.QuestScriptExecutor.loadScript(QuestScriptExecutor.java:75)
    at net.glowarion.engine.quest.QuestScriptExecutor.<init>(QuestScriptExecutor.java:29)
    at net.glowarion.engine.quest.QuestProgression.update(QuestProgression.java:77)
    at net.glowarion.engine.character.RPGCharacter.updateQuests(RPGCharacter.java:154)
    at net.glowarion.engine.character.RPGCharacter.initializeEntity(RPGCharacter.java:130)
    at net.glowarion.engine.user.User.initializeEntity(User.java:379)
    at net.glowarion.engine.BukkitEventWrapper.onPlayerJoin(BukkitEventWrapper.java:262)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2117.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
    at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370)
    at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183)
    at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178)
    at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68)
    at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255)
    at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948

emmie_findtheflower.yml

```name: emmie_findTheFlower
developer: unmut
minimum-level: 1
script: |
  def onAccept():
    # ...
  def onSecondStart(second):
    # ...

**Comment by Glowdragon** [comment]
Python hat anscheinend etwas gegen leere Funktionen.
Im Template wird daher nun die Funktion **doNothing()** eingefügt.
